### ISSUE TITLE
Tests depend on hasing algorithm in Base

### ISSUE THREAD

**Issue by KristofferC** [JuliaGeometry/Contour.jl#62]
The tests for this package fails on Julia nightly and after some poking around I believe that the tests here 

https://github.com/JuliaGeometry/Contour.jl/blob/7e1d4eae54c3f82bad07d922cca3066c5a3e6b21/test/verify_vertices.jl#L235-L248

are sensitive to the exact order the entries in the `Dict` that is returned from `get_level_cells`. The hashing has changed on Julia nightly so the tests now fail.

**Comment by sjkelly** [comment]
I am building the latest julia master and will try a fix.

**Comment by sjkelly** [comment]
Thanks again for the report. Preliminary fix is in #63. I'm not sure how much this hashing change will affect upstream plotting tests, but to be fair the contours per isolevel is not guaranteed to be ordered in any particular way. Though assuming no degeneracies or singularities the vertex count and number of contours per level should be the same regardless of hashing method.
